### ISSUE TITLE
How to add redis url?

### ISSUE THREAD

**Issue by infernoscorpion** [da-vinci-noob/telegram-affiliate-link-generator-bot#1]
Can please put a format for how to use redis server url ?

**Comment by da-vinci-noob** [comment]
@infernoscorpion - Sorry for the delayed response, I am not much active currently.
Here is the format for redis url,
`redis://localhost:6379/0`

if you have user and password you can use the below format.
`redis://usrname:password@ipaddress:6379/0`

where,
`0` -> Database
