### ISSUE TITLE
How should we add redis password for url

### ISSUE THREAD

**Issue by itzharshit** [da-vinci-noob/telegram-affiliate-link-generator-bot#2]
How should we add redis password for url

**Comment by da-vinci-noob** [comment]
@itzharshit - Sorry for the delayed response, I am not much active currently.
Did you tried this.?

`redis://usrname:password@ipaddress:6379/0`

where, 
`0` -> Database

**Comment by itzharshit** [comment]
> @itzharshit - Sorry for the delayed response, I am not much active currently.
> Did you tried this.?
> 
> `redis://usrname:password@ipaddress:6379/0`
> 
> where, 
> `0` -> Database

Hello
Thanks for your response
I am just asking how can i define it like if any environment variable available

**Comment by da-vinci-noob** [comment]
> > @itzharshit - Sorry for the delayed response, I am not much active currently.
> > Did you tried this.?
> > 
> > `redis://usrname:password@ipaddress:6379/0`
> > 
> > where, 
> > `0` -> Database
> 
> Hello
> Thanks for your response
> I am just asking how can i define it like if any environment variable available 

If you are using any deployment service like heroku.
You have an option in settings to set the environment variables.

Else if you are using terminal.
You can check this: https://askubuntu.com/a/58828

Use like below.

REDIS_URL=redis://usrname:password@ipaddress:6379/0

**Comment by itzharshit** [comment]
Ok thanks
